export default [
  {
    imageUrl:
      "https://img.freepik.com/premium-photo/background-beautiful-wallpaper-hd-best-quality-hyper-realistic-colorful-image_1078161-2015644.jpg?semt=ais_hybrid",
  },
  {
    imageUrl:
      "https://img.freepik.com/free-vector/modern-banner-with-abstract-low-poly-design_1048-14340.jpg?semt=ais_hybrid",
  },
  {
    imageUrl:
      "https://img.freepik.com/premium-photo/colorful-abstract-design-with-white-background-with-colorful-shapes-dots_951133-9829.jpg?semt=ais_hybrid",
  },
  {
    imageUrl:
      "https://img.freepik.com/free-photo/abstract-colorful-splash-3d-background-generative-ai-background_60438-2494.jpg?semt=ais_hybrid",
  },
  {
    imageUrl:
      "https://img.freepik.com/premium-photo/beautiful-design-backgrounds-free-hd-wallpapers_859483-785511.jpg?semt=ais_hybrid",
  },
  {
    imageUrl:
      "https://img.freepik.com/premium-photo/colorful-abstract-image-colorful-feathered-plant_951133-9764.jpg?semt=ais_hybrid",
  },
  {
    imageUrl:
      "https://img.freepik.com/free-vector/gradient-geometric-background_23-2149329064.jpg?semt=ais_hybrid",
  },
  {
    imageUrl:
      "https://img.freepik.com/free-vector/gradient-geometric-wallpaper_52683-55729.jpg?semt=ais_hybrid",
  },
  {
    imageUrl:
      "https://img.freepik.com/free-photo/aesthetic-wallpaper-made-abstract-geometric-shapes_23-2150300231.jpg?semt=ais_hybrid",
  },
  {
    imageUrl:
      "https://img.freepik.com/free-vector/flat-design-geometric-pattern-background_23-2149932690.jpg?semt=ais_hybrid",
  },
];
